version: "3.7"

services:
  flask:
    build: uwsgi
    container_name: uwsgi
    restart: always
    environment:
      - APP_NAME=Flask
    expose:
      - 5000

  nginx:
    build: nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:8080
